---
number:
- platform: template
  name: "AMS Number" # 0 = External Spool, 1-4 = that AMS unit
  id: ams_number
  optimistic: true
  restore_value: true
  icon: mdi:train-car-container
  min_value: 0
  max_value: 4
  step: 1
  initial_value: 0
  web_server:
    sorting_group_id: sorting_group_printer_settings
- platform: template
  name: "Slot Number"
  id: slot_number
  optimistic: true
  restore_value: true
  icon: mdi:record-circle-outline
  min_value: 1
  max_value: 4
  step: 1
  initial_value: 1
  web_server:
    sorting_group_id: sorting_group_printer_settings
