pn532_spi:
- id: rfid_reader_spi_1
  cs_pin: ${rfid1_ss_pin}
  spi_id: ${rfid1_spi_interface}
  data_rate: ${spi_data_rate}
  update_interval: ${update_interval}
  on_tag_removed:
    then:
    - script.execute:
        id: set_led_white
        led_number: 1
    - binary_sensor.template.publish:
        id: nfc_tag_present1
        state: OFF
    - lambda: |-
        id(filament_raw_data1).publish_state("");
  on_tag:
    then:
    - binary_sensor.template.publish:
        id: nfc_tag_present1
        state: ON
    - lambda: |-
        auto tag_result = rfid::read_openspool_tag(tag);
        if (!tag_result.payload.empty()) {
          id(filament_raw_data1).publish_state(tag_result.payload);
        }

        // Update states
        id(rfid_reader_spi_1_tag_parsed).publish_state(true);
        id(rfid_reader_spi_1_tag_is_openspool).publish_state(tag_result.is_valid_openspool);

        // Set LED color
        if (tag_result.is_valid_openspool) {
          id(set_led_green).execute(1);
          //TODO: Generate and send MQTT message here
          if (!tag_result.payload.empty()) {
              //TODO: should this publish mqtt payload here? 
          }
        } else {
          id(set_led_red).execute(1);
        }
    - if:
        condition:
          and:
          - mqtt.connected
          - lambda: 'return id(filament_raw_data1).state != "";'
          - lambda: 'return id(filament_raw_data1).state != "{}";'
          - binary_sensor.is_on: rfid_reader_spi_1_tag_is_openspool
          - binary_sensor.is_on: rfid_reader_spi_1_tag_parsed
        then:
        - mqtt.publish:
            topic: !lambda 'return "device/" + id(bambu_serial_number).state + "/request";'
            # 0 = external ams, first AMS is 0
            # 0 = external tray, first filament slot is tray 0
            payload: !lambda "return bambulabs::generate_mqtt_payload( id(filament_raw_data1).state, 0, 0 );"

- id: rfid_reader_spi_2
  cs_pin: ${rfid2_ss_pin}
  spi_id: ${rfid2_spi_interface}
  data_rate: ${spi_data_rate}
  update_interval: ${update_interval}
  on_tag_removed:
    then:
    - script.execute:
        id: set_led_white
        led_number: 2
    - binary_sensor.template.publish:
        id: nfc_tag_present2
        state: OFF
    - lambda: |-
        id(filament_raw_data2).publish_state("");
  on_tag:
    then:
    - binary_sensor.template.publish:
        id: nfc_tag_present2
        state: ON
    - lambda: |-
        auto tag_result = rfid::read_openspool_tag(tag);
        if (!tag_result.payload.empty()) {
          id(filament_raw_data2).publish_state(tag_result.payload);
        }

         // Update states
         id(rfid_reader_spi_2_tag_parsed).publish_state(true);
         id(rfid_reader_spi_2_tag_is_openspool).publish_state(tag_result.is_valid_openspool);

         // Set LED color
         if (tag_result.is_valid_openspool) {
           id(set_led_green).execute(2);
           //TODO: Generate and send MQTT message here
           if (!tag_result.payload.empty()) {
              //TODO: should this publish mqtt payload here? 
           }
         } else {
           id(set_led_red).execute(2);
         }
    - if:
        condition:
          and:
          - mqtt.connected
          - lambda: 'return id(filament_raw_data2).state != "";'
          - lambda: 'return id(filament_raw_data2).state != "{}";'
          - binary_sensor.is_on: rfid_reader_spi_2_tag_is_openspool
          - binary_sensor.is_on: rfid_reader_spi_2_tag_parsed
        then:
        - mqtt.publish:
            topic: !lambda 'return "device/" + id(bambu_serial_number).state + "/request";'
            # 0 = external ams, first AMS is 0
            # 0 = external tray, first filament slot is tray 0
            payload: !lambda "return bambulabs::generate_mqtt_payload( id(filament_raw_data2).state, 0, 1 );"
text_sensor:
- platform: template
  name: "NFC Raw Data 1"
  id: filament_raw_data1
  state_topic:
  internal: false # Always show raw data 1
  icon: mdi:nfc-variant
  web_server:
    sorting_group_id: sorting_group_rfid
  filters:
  - lambda: |-
      return openspool::format_display(x);
# NFC Raw Data 1-8 are hidden unless ams.yaml is included
- platform: template
  name: "NFC Raw Data 2"
  id: filament_raw_data2
  state_topic:
  internal: ${hide_ams_sensors} # Only present on raw data 1-8
  icon: mdi:nfc-variant
  web_server:
    sorting_group_id: sorting_group_rfid
  filters:
  - lambda: |-
      return openspool::format_display(x);

binary_sensor:
- platform: template
  name: "NFC Tag Present 1"
  id: nfc_tag_present1
  state_topic:
  icon: mdi:circle-double
  web_server:
    sorting_group_id: sorting_group_rfid
- id: rfid_reader_spi_1_tag_parsed
  state_topic:
  platform: template
  internal: true
- id: rfid_reader_spi_1_tag_is_openspool
  state_topic:
  platform: template
  internal: true
- platform: template
  name: "NFC Tag Present 2"
  id: nfc_tag_present2
  state_topic:
  icon: mdi:circle-double
  web_server:
    sorting_group_id: sorting_group_rfid
- id: rfid_reader_spi_2_tag_parsed
  state_topic:
  platform: template
  internal: true
- id: rfid_reader_spi_2_tag_is_openspool
  state_topic:
  platform: template
  internal: true
